kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: labourer-production
spec:
  replicas: 1
  template:
    metadata:
      name: labourer
      labels:
        app: labourer
        env: production
    spec:
      containers:
        - name: labourer
          image: gcr.io/pinacta-147615/labourer:latest
          imagePullPolicy: Always
          ports:
            - name: labourer
              containerPort: 3000
          command:
            - "labourer-exe"
          args:
            - "--host=${KUBERNETES_SERVICE_HOST}"
            - "--topic=logs"
            - "--subscription=labourer"
